{
    'name': 'Stock Enhancements',
    'summary': "Short (1 phrase/line) summary of the module's purpose",
    'description': "\nLong description of module's purpose\n    ",
    'author': "CubitIt",
    'category': 'Supply Chain/Inventory',
    'version': '0.1',
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
    'depends': ['stock'],
    'data': ['security/ir_rule.xml',
             'views/views.xml',
             'views/templates.xml'],
    'demo': ['demo/demo.xml'],
    'images': ['static/description/icon.png'],
}
